export const GET_CUSTOMER_DATA_START = 'GET_CUSTOMER_DATA_START';
export const GET_CUSTOMER_DATA_SUCCESS = 'GET_CUSTOMER_DATA_SUCCESS';
export const GET_CUSTOMER_DATA_FAILURE = 'GET_CUSTOMER_DATA_FAILURE';

export const GET_GROOMER_DATA_START = 'GET_GROOMER_DATA_START';
export const GET_GROOMER_DATA_SUCCESS = 'GET_GROOMER_DATA_SUCCESS';
export const GET_GROOMER_DATA_FAILURE = 'GET_GROOMER_DATA_FAILURE';
